############### English navigation ################

# Dropdown menu
#[[main]]
#name = "Home"
#url = "homepage/grid-right/"
#weight = 1

[[main]]
name = "About"
url = "about/"
weight = 1

# Dropdown menu
[[main]]
weight = 2
name = "Author"
hasChildren = true

    [[main]]
    parent = "Author"
    name = "이정혁"
    url = "author/이정혁-jung-hyuk-lee/"
    weight = 1

    [[main]]
    parent = "Author"
    name = "주영민"
    url = "author/주영민-youngmin-ju/"
    weight = 2

    [[main]]
    parent = "Author"
    name = "송하윤"
    url = "author/송하윤-hayun-song/"
    weight = 3


[[main]]
name = "AI_트렌드"
url = "categories/ai_트렌드/"
weight = 3

[[main]]
name = "AI_분석"
url = "categories/ai_분석/"
weight = 4

[[main]]
name = "AI_칼럼"
url = "categories/ai_칼럼/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6

#[[main]]
#weight = 8
#name = "Pages"
#hasChildren = true

#    [[main]]
#    parent = "Pages"
#    name = "Elements"
#    url = "elements/"
#    weight = 1

#    [[main]]
#    parent = "Pages"
#    name = "Tags"
#    url = "tags/photo/"
#    weight = 2

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2

#[[footer]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#weight = 3

#[[footer]]
#name = "Terms Conditions"
#url = "terms-conditions/"
#weight = 4
